import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b = await puppeteer.launch({ executablePath: CHROME, args: ["--headless=new", "--hide-scrollbars", "--force-device-scale-factor=2"] });
const p = await b.newPage();
const bad = [];
p.on("response", (r) => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url()}`); });
await p.setViewport({ width: 1440, height: 1050, deviceScaleFactor: 2 });
const t0 = Date.now();
await p.goto("https://designguide-001.vercel.app/", { waitUntil: "networkidle0", timeout: 120000 });
console.log("読み込み", Date.now() - t0, "ms");
await new Promise((r) => setTimeout(r, 900));
await p.screenshot({ path: "shots/live-top.png" });
await p.evaluate(() => document.getElementById("atlas")?.scrollIntoView());
await new Promise((r) => setTimeout(r, 1600));
await p.screenshot({ path: "shots/live-atlas.png" });
const n = await p.$$eval("[data-card]", (e) => e.length);
const imgs = await p.$$eval(".card__plate img", (e) => e.filter((i) => i.naturalWidth > 0).length);
console.log("カード", n, "枚 / 読めた図版", imgs, "枚（見えている分）");
console.log(bad.length ? "エラー: " + bad.join(", ") : "エラーなし");
await b.close();
